import type { CurriculumItem } from "./types"

export const curriculumOptions: CurriculumItem[] = [
  {
    id: "1",
    name: "Saxon Math",
    publisher: "Houghton Mifflin Harcourt",
    description:
      "A comprehensive math curriculum known for its incremental approach and continuous review, helping students master concepts through practice and repetition.",
    subjects: ["Mathematics"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Traditional", "Structured", "Mastery-based"],
    format: ["Textbook", "Workbook", "Teacher Guide"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Saxon+Math",
    url: "https://www.hmhco.com/programs/saxon-math",
    features: ["Incremental Development", "Continuous Practice", "Cumulative Assessment"],
    rating: 4.7,
    reviewCount: 856,
  },
  {
    id: "2",
    name: "Sonlight",
    publisher: "Sonlight Curriculum",
    description:
      "A literature-based, Christian homeschool curriculum that emphasizes reading great books and engaging in meaningful discussions.",
    subjects: ["Language Arts", "History", "Science", "Bible"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Literature-based", "Charlotte Mason", "Unit Study"],
    format: ["Complete Curriculum", "Instructor's Guide", "Book Sets"],
    religiousAffiliation: "Christian",
    timeCommitment: "High",
    costRange: "$$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Sonlight",
    url: "https://www.sonlight.com/",
    features: ["Literature-Rich", "All-in-One Packages", "Instructor Guides", "Global Focus"],
    rating: 4.8,
    reviewCount: 1245,
  },
  {
    id: "3",
    name: "Singapore Math",
    publisher: "Singapore Math Inc.",
    description:
      "A mathematics curriculum based on the teaching methods from Singapore, focusing on problem-solving and a deep understanding of mathematical concepts.",
    subjects: ["Mathematics"],
    gradeLevel: ["K-3", "4-6", "7-8"],
    teachingStyle: ["Mastery-based", "Conceptual", "Visual"],
    format: ["Textbook", "Workbook", "Teacher Guide"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Singapore+Math",
    url: "https://www.singaporemath.com/",
    features: ["Concrete-Pictorial-Abstract Approach", "Mental Math", "Model Drawing"],
    rating: 4.6,
    reviewCount: 723,
  },
  {
    id: "4",
    name: "Brave Writer",
    publisher: "Brave Writer LLC",
    description:
      "A language arts curriculum that focuses on developing authentic writing skills through natural, enjoyable writing experiences.",
    subjects: ["Language Arts", "Writing"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Charlotte Mason", "Relaxed", "Natural Learning"],
    format: ["Online Classes", "Digital Resources", "Physical Books"],
    religiousAffiliation: "Secular",
    timeCommitment: "Low to Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Brave+Writer",
    url: "https://bravewriter.com/",
    features: ["Poetry Teatime", "Freewriting", "Literary Analysis", "Online Classes"],
    rating: 4.9,
    reviewCount: 512,
  },
  {
    id: "5",
    name: "Apologia Science",
    publisher: "Apologia Educational Ministries",
    description:
      "A creation-based science curriculum with a conversational style that makes complex scientific concepts accessible and engaging.",
    subjects: ["Science"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Traditional", "Charlotte Mason", "Classical"],
    format: ["Textbook", "Notebooking Journal", "Lab Kit"],
    religiousAffiliation: "Christian",
    timeCommitment: "Medium to High",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Apologia",
    url: "https://apologia.com/",
    features: ["Creation-Based", "Hands-on Experiments", "Notebooking Activities"],
    rating: 4.7,
    reviewCount: 938,
  },
  {
    id: "6",
    name: "The Good and the Beautiful",
    publisher: "Jenny Phillips",
    description:
      "A comprehensive, faith-based curriculum focusing on beauty, truth, and goodness while maintaining high academic standards.",
    subjects: ["Language Arts", "History", "Science", "Math", "Art"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Charlotte Mason", "Traditional", "Unit Study"],
    format: ["Complete Curriculum", "PDF Downloads", "Physical Books"],
    religiousAffiliation: "Christian",
    timeCommitment: "Medium",
    costRange: "$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=TGATB",
    url: "https://www.goodandbeautiful.com/",
    features: ["Family-Style Learning", "Beautiful Illustrations", "Character Development"],
    rating: 4.8,
    reviewCount: 1567,
  },
  {
    id: "7",
    name: "Math-U-See",
    publisher: "Demme Learning",
    description:
      "A multi-sensory math curriculum that uses manipulatives to help students understand math concepts concretely before moving to abstract thinking.",
    subjects: ["Mathematics"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Mastery-based", "Hands-on", "Sequential"],
    format: ["Textbook", "Workbook", "Manipulatives", "Video Instruction"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Math-U-See",
    url: "https://mathusee.com/",
    features: ["Manipulatives", "Video Instruction", "Mastery Approach"],
    rating: 4.6,
    reviewCount: 892,
  },
  {
    id: "8",
    name: "Classical Conversations",
    publisher: "Classical Conversations Inc.",
    description:
      "A classical education program that combines home education with a community-based model, focusing on the classical trivium of grammar, dialectic, and rhetoric stages.",
    subjects: ["Multiple Subjects", "Classical Education"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Classical", "Community-based", "Socratic"],
    format: ["Community Program", "Guidebooks", "Memory Work"],
    religiousAffiliation: "Christian",
    timeCommitment: "High",
    costRange: "$$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=CC",
    url: "https://www.classicalconversations.com/",
    features: ["Community Days", "Memory Work", "Socratic Discussion", "Rhetoric Training"],
    rating: 4.5,
    reviewCount: 763,
  },
  {
    id: "9",
    name: "All About Reading",
    publisher: "All About Learning Press",
    description:
      "A complete reading program based on the Orton-Gillingham approach, designed to take the guesswork out of teaching reading.",
    subjects: ["Reading", "Language Arts"],
    gradeLevel: ["K-3", "4-6"],
    teachingStyle: ["Structured", "Multisensory", "Systematic"],
    format: ["Teacher's Manual", "Student Workbooks", "Readers", "Manipulatives"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=AAR",
    url: "https://www.allaboutlearningpress.com/all-about-reading/",
    features: ["Orton-Gillingham Based", "Multisensory Activities", "No Gaps Approach"],
    rating: 4.9,
    reviewCount: 1089,
  },
  {
    id: "10",
    name: "Beast Academy",
    publisher: "Art of Problem Solving",
    description:
      "An advanced math curriculum for elementary students presented in an engaging comic book format, focusing on problem-solving and critical thinking.",
    subjects: ["Mathematics"],
    gradeLevel: ["2-3", "4-6"],
    teachingStyle: ["Problem-based", "Conceptual", "Advanced"],
    format: ["Comic Books", "Practice Books", "Online Platform"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium to High",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Beast+Academy",
    url: "https://beastacademy.com/",
    features: ["Comic Book Format", "Challenging Problems", "Online Platform"],
    rating: 4.7,
    reviewCount: 456,
  },
  {
    id: "11",
    name: "BookShark",
    publisher: "BookShark LLC",
    description:
      "A literature-based, secular curriculum offering complete, four-day homeschool programs with an emphasis on reading and discussion.",
    subjects: ["Language Arts", "History", "Science", "Reading"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Literature-based", "Charlotte Mason", "Four-day Schedule"],
    format: ["Complete Curriculum", "Instructor's Guide", "Book Sets"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium to High",
    costRange: "$$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=BookShark",
    url: "https://www.bookshark.com/",
    features: ["Four-day Schedule", "Literature-Based", "Ready-to-use Lesson Plans"],
    rating: 4.6,
    reviewCount: 587,
  },
  {
    id: "12",
    name: "Easy Peasy All-in-One Homeschool",
    publisher: "Easy Peasy All-in-One Homeschool",
    description:
      "A free, complete, online Christian homeschool curriculum for all grades covering all subjects with a day-by-day schedule.",
    subjects: ["Multiple Subjects", "Complete Curriculum"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Traditional", "Eclectic", "Online"],
    format: ["Online Platform", "Free Resources"],
    religiousAffiliation: "Christian",
    timeCommitment: "Medium",
    costRange: "Free",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Easy+Peasy",
    url: "https://allinonehomeschool.com/",
    features: ["Free", "Complete Curriculum", "Online Resources", "Day-by-Day Plans"],
    rating: 4.5,
    reviewCount: 2134,
  },
  {
    id: "13",
    name: "Oak Meadow",
    publisher: "Oak Meadow Inc.",
    description:
      "A flexible, creative curriculum that combines rigorous academics with artistic expression and experiential learning.",
    subjects: ["Multiple Subjects", "Complete Curriculum"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Waldorf-inspired", "Flexible", "Nature-based"],
    format: ["Complete Curriculum", "Teacher Guides", "Student Books"],
    religiousAffiliation: "Secular",
    timeCommitment: "Medium to High",
    costRange: "$$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Oak+Meadow",
    url: "https://www.oakmeadow.com/",
    features: ["Waldorf-inspired", "Nature-based", "Artistic Elements", "Accredited Distance Learning"],
    rating: 4.7,
    reviewCount: 423,
  },
  {
    id: "14",
    name: "Memoria Press",
    publisher: "Memoria Press",
    description:
      "A classical Christian curriculum focusing on Latin, logic, and traditional learning methods with an emphasis on memorization and recitation.",
    subjects: ["Classical Studies", "Latin", "Logic", "Literature"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Classical", "Traditional", "Rigorous"],
    format: ["Complete Curriculum", "Individual Subjects", "Lesson Plans"],
    religiousAffiliation: "Christian",
    timeCommitment: "High",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Memoria+Press",
    url: "https://www.memoriapress.com/",
    features: ["Classical Approach", "Latin-centered", "Recitation", "Memory Work"],
    rating: 4.6,
    reviewCount: 378,
  },
  {
    id: "15",
    name: "Time4Learning",
    publisher: "Time4Learning",
    description:
      "An online, interactive curriculum covering preschool through high school with automated grading and record-keeping.",
    subjects: ["Multiple Subjects", "Complete Curriculum"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Online", "Interactive", "Self-paced"],
    format: ["Online Platform", "Interactive Lessons", "Automated Grading"],
    religiousAffiliation: "Secular",
    timeCommitment: "Low to Medium",
    costRange: "$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Time4Learning",
    url: "https://www.time4learning.com/",
    features: ["Interactive Lessons", "Automated Grading", "Progress Tracking", "Activity Planner"],
    rating: 4.4,
    reviewCount: 1876,
  },
  {
    id: "16",
    name: "Masterbooks",
    publisher: "New Leaf Publishing Group",
    description:
      "A creation-based, easy-to-use curriculum with a focus on biblical worldview integration across all subjects.",
    subjects: ["Multiple Subjects", "Bible", "Science", "History"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Charlotte Mason", "Traditional", "Open-and-go"],
    format: ["Textbooks", "Workbooks", "Parent Guides"],
    religiousAffiliation: "Christian",
    timeCommitment: "Low to Medium",
    costRange: "$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Masterbooks",
    url: "https://www.masterbooks.com/",
    features: ["Creation-based", "Easy-to-use", "Affordable", "Biblical Integration"],
    rating: 4.8,
    reviewCount: 945,
  },
  {
    id: "17",
    name: "Outschool",
    publisher: "Outschool, Inc.",
    description:
      "An online marketplace of live, interactive classes covering a wide range of subjects and interests for ages 3-18.",
    subjects: ["Multiple Subjects", "Specialized Topics", "Electives"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Online", "Interactive", "Class-based"],
    format: ["Live Online Classes", "Small Groups", "Individual Lessons"],
    religiousAffiliation: "Secular",
    timeCommitment: "Variable",
    costRange: "$ to $$$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Outschool",
    url: "https://outschool.com/",
    features: ["Live Classes", "Diverse Topics", "Flexible Scheduling", "Expert Teachers"],
    rating: 4.7,
    reviewCount: 3245,
  },
  {
    id: "18",
    name: "Ambleside Online",
    publisher: "Ambleside Schools International",
    description:
      "A free Charlotte Mason curriculum using high-quality literature and primary sources with detailed schedules and resource lists.",
    subjects: ["Multiple Subjects", "Literature", "Nature Study"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Charlotte Mason", "Literature-based", "Nature-focused"],
    format: ["Book Lists", "Curriculum Guides", "Free Resources"],
    religiousAffiliation: "Christian",
    timeCommitment: "Medium to High",
    costRange: "$ (cost of books only)",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Ambleside",
    url: "https://www.amblesideonline.org/",
    features: ["Free Curriculum", "Living Books", "Nature Study", "Character Development"],
    rating: 4.8,
    reviewCount: 687,
  },
  {
    id: "19",
    name: "Khan Academy",
    publisher: "Khan Academy",
    description:
      "A free online learning platform offering practice exercises, instructional videos, and a personalized learning dashboard across K-14 subjects.",
    subjects: ["Mathematics", "Science", "Computing", "Arts & Humanities"],
    gradeLevel: ["K-3", "4-6", "7-8", "9-12"],
    teachingStyle: ["Online", "Self-paced", "Mastery-based"],
    format: ["Online Platform", "Video Lessons", "Practice Exercises"],
    religiousAffiliation: "Secular",
    timeCommitment: "Variable",
    costRange: "Free",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Khan+Academy",
    url: "https://www.khanacademy.org/",
    features: ["Free", "Video Instruction", "Practice Problems", "Progress Tracking"],
    rating: 4.9,
    reviewCount: 5678,
  },
  {
    id: "20",
    name: "Blossom & Root",
    publisher: "Blossom & Root",
    description:
      "A nature-based, secular curriculum inspired by Charlotte Mason and Waldorf methods, focusing on creativity, nature connection, and gentle academics.",
    subjects: ["Language Arts", "Science", "Nature Study", "Art", "History"],
    gradeLevel: ["K-3", "4-6"],
    teachingStyle: ["Charlotte Mason", "Waldorf-inspired", "Nature-based"],
    format: ["PDF Downloads", "Parent Guides", "Activity Books"],
    religiousAffiliation: "Secular",
    timeCommitment: "Low to Medium",
    costRange: "$",
    imageUrl: "/placeholder.svg?height=200&width=300",
    logoUrl: "/placeholder.svg?height=60&width=120&text=Blossom+%26+Root",
    url: "https://blossomandroot.com/",
    features: ["Nature-based", "Gentle Academics", "Creative Activities", "Affordable"],
    rating: 4.8,
    reviewCount: 342,
  },
]

export const curriculumData = curriculumOptions

export const subjectOptions = [
  "Mathematics",
  "Language Arts",
  "Science",
  "History",
  "Reading",
  "Writing",
  "Bible",
  "Classical Studies",
  "Latin",
  "Logic",
  "Literature",
  "Art",
  "Multiple Subjects",
  "Complete Curriculum",
  "Specialized Topics",
  "Electives",
  "Nature Study",
  "Computing",
  "Arts & Humanities",
]

export const gradeLevelOptions = ["K-3", "2-3", "4-6", "7-8", "9-12"]

export const teachingStyleOptions = [
  "Traditional",
  "Structured",
  "Mastery-based",
  "Literature-based",
  "Charlotte Mason",
  "Unit Study",
  "Conceptual",
  "Visual",
  "Relaxed",
  "Natural Learning",
  "Classical",
  "Hands-on",
  "Sequential",
  "Community-based",
  "Socratic",
  "Multisensory",
  "Systematic",
  "Problem-based",
  "Advanced",
  "Four-day Schedule",
  "Eclectic",
  "Online",
  "Waldorf-inspired",
  "Flexible",
  "Nature-based",
  "Rigorous",
  "Interactive",
  "Self-paced",
  "Open-and-go",
  "Class-based",
]

export const formatOptions = [
  "Textbook",
  "Workbook",
  "Teacher Guide",
  "Complete Curriculum",
  "Instructor's Guide",
  "Book Sets",
  "Online Classes",
  "Digital Resources",
  "Physical Books",
  "Notebooking Journal",
  "Lab Kit",
  "PDF Downloads",
  "Manipulatives",
  "Video Instruction",
  "Community Program",
  "Guidebooks",
  "Memory Work",
  "Teacher's Manual",
  "Student Workbooks",
  "Readers",
  "Comic Books",
  "Practice Books",
  "Online Platform",
  "Free Resources",
  "Interactive Lessons",
  "Automated Grading",
  "Live Online Classes",
  "Small Groups",
  "Individual Lessons",
  "Book Lists",
  "Curriculum Guides",
  "Video Lessons",
  "Practice Exercises",
  "Parent Guides",
  "Activity Books",
]

export const religiousAffiliationOptions = ["Secular", "Christian", "Faith-neutral"]

export const timeCommitmentOptions = ["Low", "Low to Medium", "Medium", "Medium to High", "High", "Variable"]

export const costRangeOptions = ["Free", "$", "$$", "$$$", "$ to $$$", "$ (cost of books only)"]
